### ISSUE TITLE
FR: Custom solid colors theme

### ISSUE THREAD

**Issue by manyfew** [Paperfeed/LiuChan#4]
It would be nice to be able to set up custom background colors.

I really like the Pleco theme because it's clean, it just fits in well with the whole Windows 10 look and feel. But I don't like the thick top and bottom edges.

Users could select one of the predefined themes or a "custom" them that would enable the following options:

- Background color: solid color picker
- Border thickness
- Border color
- Corner shape: round | square
- Drop shadow: enabled | disabled

Thank you!

**Comment by Paperfeed** [comment]
v1.1.0 now has customisation included.
