### ISSUE TITLE
Tone colors on Chinese characters cannot be disabled

### ISSUE THREAD

**Issue by manyfew** [Paperfeed/LiuChan#6]
It seems tone colors on Chinese characters cannot be disabled, neither in the Options preview nor the actual pop-up:

![tone colors](https://user-images.githubusercontent.com/11704566/32402425-e7b948bc-c15e-11e7-933f-e17432afe65b.png)

Thanks!

**Comment by Paperfeed** [comment]
v1.1.0 now has customisation included. This particular bug has been fixed along with that.
